---
title: 'digital:success – digital and IT innovation by design:success'
timezone: UTC
email: success@designsuccess.com
description: 'Award-winning digital pioneers, taking validated innovation and making them come digitally alive – fast! App development, digital prototyping, artificial intelligence – and much much more.'
keywords: 'Digital success, digital:success, design:success, design success, Digital agency, innovation consultancy, app development, digital innovation, IT, prototyping, enterprise solution, artificial intelligence'
og_image: '/assets/img/og_image.jpg'
url: http://designsuccess.com/digitalsuccess
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- webpack
sass:
  style: compressed
github:
- metadata
