---
title: 'transform:now - market research IT & digital innovation implementation'
timezone: UTC
email: success@designsuccess.com
description: 'Award-winning digital pioneers, taking validated innovation and making them come digitally alive – fast! App development, digital prototyping, artificial intelligence – and much much more.'
keywords: 'Transform now, transform:now, design:success, design success, Digital agency, innovation consultancy, app development, digital innovation, IT, prototyping, enterprise solution, artificial intelligence'
og_image: '/assets/img/og_image.jpg'
url: http://designsuccess.com/transformnow
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- webpack
sass:
  style: compressed
github:
- metadata
