---
title: 'digital:success'
timezone: UTC
email: success@designsuccess.com
description: Digital success
og_image: "/assets/img/og_image.png"
baseurl: 
url: http://digitalsuccess.com
markdown: kramdown
plugins:
- jekyll-feed
- octopress-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- webpack
sass:
  style: compressed
github:
- metadata
